{% set name = "libsndfile" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/libsndfile/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.xz  
  sha256: 3799ca9924d3125038880367bf1468e53a1b7e3686a934f098b7e1d286cdb80e  

build:
  number: 1
  run_exports:
        # https://abi-laboratory.pro/?view=timeline&l=libsndfile
    - {{ pin_subpackage(name, max_pin="x.x") }}
  skip: true  # [s390x or win]

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [not win]
    - python
    - pkg-config  # [unix]
  host:
    - libflac 1.4.3
    - libvorbis 1.3.7
    - libogg 1.3.5
    - libopus 1.3
    - lame 3.100
    - mpg123 1.30.0
  run:
    - {{ pin_compatible('mpg123', max_pin='x.x')}}

test:
  commands:
    - test -f $PREFIX/lib/libsndfile${SHLIB_EXT}  # [not win]

    # try to run one of the commands (--help returns 1, so make that OK)
    - sndfile-info --help || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]

about:
  home: https://libsndfile.github.io/libsndfile/
  dev_url: https://github.com/libsndfile/libsndfile
  doc_url: https://libsndfile.github.io/libsndfile/
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: libsndfile is a C library for reading and writing files containing sampled audio data.
  description: |
    libsndfile is a C library for reading and writing files containing sampled sound 
    (such as MS Windows WAV and the Apple/SGI AIFF format) through one standard library interface.

extra:
  recipe-maintainers:
    - hbredin
    - thomasfillon
    - SylvainCorlay
    - wolfv
    - JohanMabille
    - bmcfee
