{% set name = "libsndfile" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # libsndfile 1.1.0 shipped with slightly broken package archives
  # these should be reconciled into one download in a subsequent release
  url: https://github.com/libsndfile/{{ name }}/archive/refs/tags/{{ version }}.zip  # [win]
  sha256: 3799ca9924d3125038880367bf1468e53a1b7e3686a934f098b7e1d286cdb80e  # [win]
  url: https://github.com/libsndfile/{{ name }}/releases/download/{{ version }}/{{ name }}-{{ version }}.tar.xz  # [not win]
  sha256: 3799ca9924d3125038880367bf1468e53a1b7e3686a934f098b7e1d286cdb80e  # [not win]
  patches:
    # the libs private sections of pkgconfig is only useful when statically
    # linking which we do not use.
    # On windows, this results in an empty "-l" which breakds downstream packages
    # since the linker tries to link to ".libs"
    # https://github.com/conda-forge/gst-plugins-bad-feedstock/pull/20#issuecomment-1336553304
    # it may be related to
    # https://github.com/libsndfile/libsndfile/issues/827
    # But I don't have time to investigate too much
    - disable_libs_private_pkgconfig.patch


build:
  number: 0
  run_exports:
        # https://abi-laboratory.pro/?view=timeline&l=libsndfile
    - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make   # [not win]
    - cmake  # [win]
    - ninja  # [win]
    - python
    - pkg-config  # [unix]
  host:
    - libflac
    - libvorbis
    - libogg
    - libopus
    - lame
    - mpg123

test:
  commands:
    - test -f $PREFIX/lib/libsndfile${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\sndfile.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\sndfile.lib exit 1  # [win]

    # try to run one of the commands (--help returns 1, so make that OK)
    - sndfile-info --help || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - sndfile-info --help || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]

about:
  home: http://www.mega-nerd.com/libsndfile
  dev_url: https://github.com/libsndfile/libsndfile
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: COPYING
  summary: libsndfile - a C library for reading and writing files containing sampled sound (such as MS Windows WAV and the Apple/SGI AIFF format) through one standard library interface

extra:
  recipe-maintainers:
    - hbredin
    - thomasfillon
    - SylvainCorlay
    - wolfv
    - JohanMabille
    - bmcfee
