{% set name = "libsndfile" %}
{% set version = "1.0.29" %}
{% set sha256 = "2ba20d44817c8176f097ab25eff44ef0aeec9e00973def5a7174c5ae0764b22f" %}

package:
    name: {{ name|lower }}
    version: {{ version }}

source:
    fn: {{ name }}-{{ version }}.tar.gz
    url: https://github.com/erikd/{{ name }}/releases/download/v{{ version }}/{{ name }}-{{ version }}.tar.bz2
    sha256: {{ sha256 }}

build:
    number: 0
    run_exports:
        # https://abi-laboratory.pro/?view=timeline&l=libsndfile
        - {{ pin_subpackage(name, max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [win]
    - make  # [not win]
    - ninja  # [win]
    - python
  host:
    - libflac
    - libvorbis
    - libogg
  # libflac, libvorbis and libogg don't specify run exports
  run:
    - libflac
    - libvorbis
    - libogg
test:
  commands:
    - test -f $PREFIX/lib/libsndfile${SHLIB_EXT}  # [not win]
    - if not exist %PREFIX%\\Library\\bin\\sndfile.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\sndfile.lib exit 1  # [win]

    # try to run one of the commands (--help returns 1, so make that OK)
    - sndfile-info --help || ec=$?; if [ $ec -gt 1 ]; then exit $ec; fi  # [not win]
    - sndfile-info --help || if !ERRORLEVEL! LEQ 1 cmd /c "exit /b 0"  # [win]

about:
    home: http://www.mega-nerd.com/libsndfile
    dev_url: https://github.com/erikd/libsndfile
    license: LGPL-2.1-or-later
    license_family: LGPL
    license_file: COPYING
    summary: "libsndfile - a C library for reading and writing files containing sampled sound (such as MS Windows WAV and the Apple/SGI AIFF format) through one standard library interface"

extra:
  recipe-maintainers:
    - hbredin
    - thomasfillon
    - SylvainCorlay
    - wolfv
    - JohanMabille
