travis:
  secure:
    BINSTAR_TOKEN: ginzZC0SplYjz0+5fdYgZjOuiklbR3XKPcfNM13TxkcbmaHmEuUslnBCl8cz/Ey2Z8cezZp/1dAlA8NqPTWjOa0uNGvhWWHeGQcj5WgLl67sfRFZxoW76ydb38FT8Pd8y5J4Z5mAMVEO4yL9QljSlLZ+uxxrdmoe7tdaCl29BFsWzQBCz6p05K9N4OYClR3/Jn/53OOVaUPqH3JxVO3hFh1f4b7Uim/ihmdcbWYsys8r5UU0miAv8L8DpLSLJk/LtequO5BfIjnyqodrtTGPhy2GznVaZx70nBlBioN0OIIr76+WokigZE3RGYLHXK/7WcYuCzJg0FKynuoh9jfAd9US5/lXmgDS+IArA5mTLCwpcJFbjQ+aVlqYKiIsTcKq353gnTg7rKoECZ2hz03ulM7HHNYGtqEizdWEf/wkrTm1JDkQZWNCzu+2rHEliDDYsh+6+89Z5rDS92gkNf3pz/EZUeTI12fM3d4AyqwgUza6/kImnem+GUfkEvlH7NQNeBAz+JAaA16moJywWjaA+V/AkCtO2hzuNRnBd3ozM3F3+XybPtpxzTvl4MvSGbynEoBlFOpoxcvKbfaAGKMaQQpvjcl5cUSWLcSvTwGCRGStX0eqAprlOtYsOUNSymkZUA/Qb0qzwdmHQ6FQyMiWAyjfjZ4DwAV6JOkVHocFJgI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
